# Tensor Initializers

In [2]:
def ones_init():
    value = []
    for _ in range(1_000_000):
        value.append(1)
        
%timeit ones_init()

32.3 ms ± 390 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
%timeit [1 for _ in range(1_000_000)]

17.3 ms ± 586 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit [1] * 1_000_000

2.69 ms ± 66.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
import numpy as np
%timeit np.ones(1_000_000)

537 µs ± 39.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [47]:
import math
def sqrt_iter():
    values = []
    for ii in range(1_000_000):
        values.append(math.sqrt(ii))
    return values
# values = sqrt_iter()
%timeit sqrt_iter()

87.5 ms ± 1.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [48]:
def sqrt_iter_preallocate():
    values = [0] * 1_000_000
    for ii in range(1_000_000):
        values[ii] = math.sqrt(ii)
    return values
%timeit sqrt_iter_preallocate()

78.4 ms ± 828 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# Concatenation, Stacking, and Splitting

In [6]:
import numpy as np

# one dimensional vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.append(a, b, axis=None)

c

array([1, 2, 3, 4, 5, 6])

In [7]:
# two dimensional matrices
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[-1, -2, -3], [-4, -5, -6]])
z = np.append(x, y, axis=None)

z

array([ 1,  2,  3,  4,  5,  6, -1, -2, -3, -4, -5, -6])

In [8]:
# one dimensional vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# specifying axis=1 will throw AxisError: 
# axis 1 is out of bounds for an array of dimension 1
c = np.append(a, b, axis=0)

c

array([1, 2, 3, 4, 5, 6])

In [10]:
# two dimensional matrices
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[-1, -2, -3], [-4, -5, -6]])
# concatenate along axis=0
z = np.append(x, y, axis=0)
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [-1, -2, -3],
       [-4, -5, -6]])

In [9]:
# concatenate along axis=1
z = np.append(x, y, axis=1)
z

array([[ 1,  2,  3, -1, -2, -3],
       [ 4,  5,  6, -4, -5, -6]])

# Reshaing

## Expanding dimensions


In [11]:
import numpy as np

X = np.random.rand(3, 2)
# using expand dims
y1 = np.expand_dims(X, axis=1)
# using None slicing
y2 = X[:, None, :]
# using np.newaxis
y3 = X[:, np.newaxis, :]

y1

array([[[0.99080835, 0.13565953]],

       [[0.07737893, 0.07012417]],

       [[0.32714517, 0.33062919]]])

In [12]:
y2

array([[[0.99080835, 0.13565953]],

       [[0.07737893, 0.07012417]],

       [[0.32714517, 0.33062919]]])

In [13]:
y3

array([[[0.99080835, 0.13565953]],

       [[0.07737893, 0.07012417]],

       [[0.32714517, 0.33062919]]])

## Squeezing dimensions

In [14]:
import numpy as np
X = np.random.rand(3, 1, 2)
# using squeeze
y1 = np.squeeze(X, axis=1)
# using slicing
y2 = X[:, 0, :]

In [15]:
y1

array([[0.92486206, 0.41168012],
       [0.23835872, 0.67035579],
       [0.61231402, 0.98312038]])

In [16]:
y2

array([[0.92486206, 0.41168012],
       [0.23835872, 0.67035579],
       [0.61231402, 0.98312038]])

## AtleastNDims

In [18]:
import numpy as np
x = np.array(6)
y = np.expand_dims(x, axis=0) # np.array([6])
y = np.expand_dims(y, axis=0) # np.array([[6]])
y = np.expand_dims(y, axis=0) # np.array([[[6]]])
y

array([[[6]]])

In [20]:
x = np.array(6)
y = np.atleast_3d(x) # np.array([[[6]]])
y

array([[[6]]])

In [24]:
x = np.array([[[[[6]]]]]) # 5-dimensional
y = np.atleast_3d(x) # still 5-dimensional
x.ndim

5

In [25]:
y.ndim

5

## Transpose

In [26]:
import numpy as np
image_tf = np.random.rand(8, 32, 15, 3)
image_torch = np.transpose(image_tf, axes=[0, 3, 1, 2])
image_tf

array([[[[0.62888589, 0.42354759, 0.0974367 ],
         [0.02968999, 0.95489349, 0.60553961],
         [0.27722497, 0.50629883, 0.0949888 ],
         ...,
         [0.03700826, 0.94352774, 0.44432409],
         [0.24049635, 0.50726072, 0.35856459],
         [0.98640618, 0.77434935, 0.73238741]],

        [[0.23076011, 0.59771891, 0.47583868],
         [0.08205684, 0.21995952, 0.2899454 ],
         [0.95572242, 0.31315042, 0.99505286],
         ...,
         [0.31815611, 0.79658114, 0.57400471],
         [0.42931661, 0.81023522, 0.71925696],
         [0.77579607, 0.37452966, 0.26525464]],

        [[0.35996363, 0.93958835, 0.90060627],
         [0.94325785, 0.75557186, 0.11888263],
         [0.46309227, 0.14930962, 0.03079653],
         ...,
         [0.13710697, 0.56934223, 0.46858994],
         [0.41212876, 0.2637237 , 0.22152135],
         [0.79462808, 0.06144676, 0.0293928 ]],

        ...,

        [[0.23783396, 0.97463031, 0.81701217],
         [0.91754005, 0.27871873, 0.34189611]

In [27]:
image_torch = np.swapaxes(image_tf, 1, 3) # (8, 3, 15, 32)
print(image_torch.shape)
image_torch = np.swapaxes(image_torch, 2, 3) # (8, 3, 32, 15)
print(image_torch.shape)

(8, 3, 15, 32)
(8, 3, 32, 15)


# Case Study: Image Normalization

In [43]:
import numpy as np

def normalize_image(image):
    """Normalize image pixel values to be between 0 and 1"""
    # image shape (height, width, channel)
    min_val = np.min(image) # scalar
    max_val = np.max(image) # scalar
    normalized_img = (image - min_val) / (max_val - min_val + 1e-6)

    return normalized_img

image = np.random.randn(28, 28, 3)
print("Before normalization:", image.min(), ",", image.max())
normalized_img = normalize_image(image)
print("After normalization:", normalized_img.min(), ",", normalized_img.max())

Before normalization: -3.1193620454833173 , 2.5491148018992122
After normalization: 0.0 , 0.9999998235857973


In [44]:
import numpy as np

def normalize_image_batch(images):
    """Normalize image pixel values to be between 0 and 1"""
    # image shape (batch_size, height, width, channel)
    # min / max (batch_size, 1, 1, 1)
    min_val = np.min(images, axis=(1, 2, 3), keepdims=True)
    max_val = np.max(images, axis=(1, 2, 3), keepdims=True)
    normalized_img = (images - min_val) / (max_val - min_val + 1e-6)

    return normalized_img

image = np.random.randn(32, 28, 28, 3)
print("Before normalization:", image.min(), ",", image.max())
normalized_img = normalize_image_batch(image)
print("After normalization:", normalized_img.min(), ",", normalized_img.max())

Before normalization: -4.629566179286963 , 4.185421603136554
After normalization: 0.0 , 0.9999998790137918


# Case Study: Pearson's Correlation

In [45]:
import numpy as np

def faster_corr(X, Y):
    """
    A faster way to compute Pearson's correlation
    between corresponding rows of two matrices
    """
    # zero means
    X = X - np.mean(X, axis=1, keepdims=True) 
    Y = Y - np.mean(Y, axis=1, keepdims=True)
    # L2 normalization
    X = X / np.sqrt(np.sum(X**2, axis=1, keepdims=True))
    Y = Y / np.sqrt(np.sum(Y**2, axis=1, keepdims=True))
    R = np.sum(X*Y, axis=1)

    return R

X = np.random.rand(10, 20)
Y = np.random.rand(10, 20)

R = faster_corr(X, Y)
R

array([-0.06100263, -0.22833885,  0.28459925,  0.04596815,  0.11139861,
       -0.22759549,  0.13234171,  0.27218793, -0.35384352,  0.40702733])

# Case Study: Pair-wise Difference

In [46]:
import numpy as np

def pairwise_diff(A, B):
    """
    Calculate the pair-wise difference between 
    each element of the two vectors of length N and M, 
    respectively, and return a matrix of shape M x N
    * A: vector of length M
    * B: vector of length N
    """
    A = np.asarray(A).flatten()[:, np.newaxis]
    B = np.asarray(B).flatten()[np.newaxis, :]
    return A - B

A = np.array([1, 2, 3, 4, 5])
B = np.array([-1, -2, -3])
D = pairwise_diff(A, B)
D

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

# Magic Squares

In [49]:
import numpy as np

def _odd_order_magic(n: int):
    """Make Siamese odd-order magic squares via Latin squares."""
    # Initialize p = i / j, used for 
    # brodcasting later -> shape n x 1
    p = np.arange(n)[:, None]
    # make L_b
    L_b = np.mod(p + p.T - (n - 1) // 2, n)
    # make L_u
    L_u = np.mod(p + 2 * p.T - n + 1, n)
    # make the magic square
    S = n * L_b + L_u + np.ones_like(L_b)

    return S

def _doubly_even_order_magic(n: int):
    """Use X method to construct doubly even magic squares."""
    # e.g. n=8, (64, )
    S = np.arange(n**2, 0, -1)
    # Split into 4x4 blocks (2, 4, 2, 4)
    S = S.reshape((n//4, 4, n//4, 4))
    # Create the X mask
    X = np.eye(4, dtype=S.dtype) * (n**2 + 1)
    X = X + np.fliplr(X)
    # (1, 4, 1, 4)
    X = X[None, :, None, :]
    # Subtract under absolute value
    S = np.abs(S - X)
    # Reshape (8, 8)
    S = S.reshape((n, n))

    return S

def _singly_even_order_magic(n: int):
    """Use LUX method to construct singly even magic squares."""
    # Compute size constants
    m = n // 2 # odd
    k = (m - 1) // 2
    # Initialize the 3 filling variants
    L = np.array([[4, 1], [2, 3]])
    U = np.array([[1, 4], [2, 3]])
    X = np.array([[1, 4], [3, 2]])
    # Create k-rows of L-filled blocks
    M_L = np.full((k, m, 2, 2), L)
    # Create a row of L-filled blocks, 
    # except the middle column is filled with U
    M_LU = np.concatenate([
        np.full((1, k, 2, 2), L),
        U[None, None, :, :],
        np.full((1, k, 2, 2), L),
    ], axis=1)
    # Create a row of U-filled blocks,
    # except the middle column is filled with L
    M_UL = np.concatenate([
        np.full((1, k, 2, 2), U),
        L[None, None, :, :],
        np.full((1, k, 2, 2), U),
    ], axis=1)
    # Fill the rest the k-1 rows with X
    M_X = np.full((k-1, m, 2, 2), X)
    # Combine all the sub-blocks (p, p, 2, 2)
    M = np.concatenate([
        M_L, M_LU, M_UL, M_X
    ], axis=0)
    # Initialize the Simaese odd order magic square
    S = _odd_order_magic(m)
    # Apply the Siamese mapping formula
    M += 4 * (S[:, :, None, None] - 1)
    # Reshaping back to n x n
    M = np.swapaxes(M, 1, 2).reshape((n, n))

    return M

def magic(n: int):
    """Construct magic squares of order n."""
    n = int(n) # make sure n is integer
    if n < 3: # check value of n
        raise(ValueError("n must be > 2."))
    if n % 2 == 1: # odd case
        return _odd_order_magic(n)
    elif n % 4 == 0: # doubly even
        return _doubly_even_order_magic(n)
    else: # assume singly even
        return _singly_even_order_magic(n)


In [55]:
magic(3)

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

In [51]:
magic(4)

array([[ 1, 15, 14,  4],
       [12,  6,  7,  9],
       [ 8, 10, 11,  5],
       [13,  3,  2, 16]])

In [52]:
magic(6)

array([[32, 29,  4,  1, 24, 21],
       [30, 31,  2,  3, 22, 23],
       [12,  9, 17, 20, 28, 25],
       [10, 11, 18, 19, 26, 27],
       [13, 16, 36, 33,  5,  8],
       [14, 15, 34, 35,  6,  7]])